name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: 'npm run build:production'
      - name: Release
        env:
          GIT_AUTHOR_NAME: 'oblakbot'
          GIT_AUTHOR_EMAIL: 'sibin.grasic+bot@oblak.studio'
          GIT_COMMITTER_NAME: 'oblakbot'
          GIT_COMMITTER_EMAIL: 'sibin.grasic+bot@oblak.studio'
          GITHUB_TOKEN: ${{ secrets.OBLAK_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run release
